services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydb-local
    ports:
      - "2136:2136"  # gRPC
      - "8765:8765"  # web ui
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - GRPC_TLS_PORT=0
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
